In [9]:
import pandas as pd

In [10]:
car_data = pd.read_csv('../data/raw/used_cars_cleaned.csv')

In [11]:
car_data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price
0,ford,utility police interceptor base,2013,51000.0,e85 flex fuel,300.0hp 3.7l v6 cylinder engine flex fuel capa...,6-speed a/t,black,black,at least 1 accident or damage reported,yes,10300.0
1,hyundai,palisade sel,2021,34742.0,gasoline,3.8l v6 24v gdi dohc,8-speed automatic,moonlight cloud,gray,at least 1 accident or damage reported,yes,38005.0
2,lexus,rx 350 rx 350,2022,22372.0,gasoline,3.5 liter dohc,automatic,blue,black,none reported,yes,54598.0
3,infiniti,q50 hybrid sport,2015,88900.0,hybrid,354.0hp 3.5l v6 cylinder engine gas/electric h...,7-speed a/t,black,black,none reported,yes,15500.0
4,audi,q3 45 s line premium plus,2021,9835.0,gasoline,2.0l i4 16v gdi dohc turbo,8-speed automatic,glacier white metallic,black,none reported,yes,34999.0

In [12]:
car_data.columns

Index(['brand', 'model', 'model_year', 'milage', 'fuel_type', 'engine',
       'transmission', 'ext_col', 'int_col', 'accident', 'clean_title',
       'price'],
      dtype='object')

In [13]:
car_data['car_age'] = 2025 - car_data['model_year']
car_data.head()

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age
0,ford,utility police interceptor base,2013,51000.0,e85 flex fuel,300.0hp 3.7l v6 cylinder engine flex fuel capa...,6-speed a/t,black,black,at least 1 accident or damage reported,yes,10300.0,12
1,hyundai,palisade sel,2021,34742.0,gasoline,3.8l v6 24v gdi dohc,8-speed automatic,moonlight cloud,gray,at least 1 accident or damage reported,yes,38005.0,4
2,lexus,rx 350 rx 350,2022,22372.0,gasoline,3.5 liter dohc,automatic,blue,black,none reported,yes,54598.0,3
3,infiniti,q50 hybrid sport,2015,88900.0,hybrid,354.0hp 3.5l v6 cylinder engine gas/electric h...,7-speed a/t,black,black,none reported,yes,15500.0,10
4,audi,q3 45 s line premium plus,2021,9835.0,gasoline,2.0l i4 16v gdi dohc turbo,8-speed automatic,glacier white metallic,black,none reported,yes,34999.0,4

In [14]:
car_data['milage_per_year'] = car_data['milage'] / car_data['car_age'].replace(0, 1)

In [15]:
car_data.sample(10)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,milage_per_year
2933,gmc,yukon xl 1500 slt,2015,145000.0,gasoline,355.0hp 5.3l 8 cylinder engine gasoline fuel,6-speed a/t,white,beige,none reported,yes,24950.0,10,14500.000000
3561,toyota,prius plug-in base,2014,106000.0,plug-in hybrid,134.0hp 1.8l 4 cylinder engine plug-in electri...,a/t,green,beige,at least 1 accident or damage reported,yes,11800.0,11,9636.363636
1792,bmw,m3 base,2001,60000.0,gasoline,333.0hp 3.2l straight 6 cylinder engine gasoli...,6-speed m/t,black,gray,none reported,yes,25000.0,24,2500.000000
2578,ford,fusion se,2016,68000.0,gasoline,175.0hp 2.5l 4 cylinder engine gasoline fuel,a/t,black,black,none reported,yes,12500.0,9,7555.555556
2586,honda,s2000 cr,2008,44300.0,gasoline,237.0hp 2.2l 4 cylinder engine gasoline fuel,m/t,yellow,black,none reported,yes,62000.0,17,2605.882353
2949,lamborghini,gallardo lp550-2,2013,22000.0,gasoline,550.0hp 5.2l 10 cylinder engine gasoline fuel,6-speed a/t,black,black,none reported,yes,150000.0,12,1833.333333
264,jeep,gladiator rubicon,2022,8794.0,gasoline,285.0hp 3.6l v6 cylinder engine gasoline fuel,a/t,white,black,none reported,yes,54000.0,3,2931.333333
1955,porsche,panamera 4s,2017,42596.0,gasoline,440.0hp 2.9l v6 cylinder engine gasoline fuel,transmission w/dual shift mode,black,black,none reported,yes,78000.0,8,5324.500000
1679,mercury,capri xr2,1993,120644.0,–,–,5-speed m/t,green,gray,none reported,yes,4200.0,32,3770.125000
1359,bmw,m3 base,2008,133500.0,gasoline,414.0hp 4.0l 8 cylinder engine gasoline fuel,6-speed m/t,gray,black,none reported,yes,18500.0,17,7852.941176

## I just want to do some tests to see the relations

### Starting off with milage and the price

In [17]:
from scipy.stats import chi2_contingency

# Example: 4 bins each
car_data['milage_bin'] = pd.qcut(car_data['milage'], q=4, labels=['Low', 'Medium', 'High', 'Very High'])
car_data['price_bin'] = pd.qcut(car_data['price'], q=4, labels=['Cheap', 'Moderate', 'Expensive', 'Luxury'])

In [18]:
contingency_table = pd.crosstab(car_data['milage_bin'], car_data['price_bin'])
print(contingency_table)

price_bin   Cheap  Moderate  Expensive  Luxury
milage_bin
Low             7        85        279     562
Medium         49       260        344     279
High          246       372        234      80
Very High     631       237         55      10

In [20]:
chi2, p, dof, expected = chi2_contingency(contingency_table)

print("Chi2 Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("P-Value:", p)

# Interpretation
if p < 0.05:
    print("🔍 Mileage and Price are likely dependent (p < 0.05).")
else:
    print("✅ No strong evidence of dependency between Mileage and Price (p ≥ 0.05).")

Chi2 Statistic: 2208.894643797451
Degrees of Freedom: 9
P-Value: 0.0
🔍 Mileage and Price are likely dependent (p < 0.05).

### I'm gonna try to do the same with the age of the car and the price

In [22]:
# Example: 4 bins each
car_data['age_bin'] = pd.qcut(car_data['car_age'], q=4, labels=['New', 'Like New', 'Old', 'Very Old'])

In [23]:
contingency_table = pd.crosstab(car_data['age_bin'], car_data['price_bin'])
print(contingency_table)

price_bin  Cheap  Moderate  Expensive  Luxury
age_bin
New            1       129        395     569
Like New      38       259        312     211
Old          306       389        144      99
Very Old     588       177         61      52

In [24]:
chi2, p, dof, expected = chi2_contingency(contingency_table)

print("Chi2 Statistic:", chi2)
print("Degrees of Freedom:", dof)
print("P-Value:", p)

# Interpretation
if p < 0.05:
    print("🔍 Car Age and Price are likely dependent (p < 0.05).")
else:
    print("✅ No strong evidence of dependency between Car Age and Price (p ≥ 0.05).")

Chi2 Statistic: 2033.9867846479501
Degrees of Freedom: 9
P-Value: 0.0
🔍 Car Age and Price are likely dependent (p < 0.05).

### Extracting the engine size (numerics)

In [30]:
import re
# Extract engine size in liters (e.g., "3.7L")
car_data['engine_size'] = car_data['engine'].str.extract(r'(\d+(?:\.\d+)?)\s*[lL]', flags=re.IGNORECASE).astype(float)

In [33]:
car_data.sample(10)

,brand,model,model_year,milage,fuel_type,engine,transmission,ext_col,int_col,accident,clean_title,price,car_age,milage_per_year,milage_bin,price_bin,age_bin,engine_size
3329,volvo,xc70 t6 platinum,2012,69000.0,gasoline,300.0hp 3.0l straight 6 cylinder engine gasoli...,a/t,silver,black,at least 1 accident or damage reported,yes,15900.0,13,5307.692308,High,Cheap,Old,3.0
272,bmw,m8 competition,2020,10906.0,gasoline,4.4 liter twin turbo,automatic,donington grey metallic,black,none reported,yes,96998.0,5,2181.200000,Low,Luxury,New,4.4
215,toyota,highlander xle,2020,61341.0,gasoline,3.5l v6 24v pdi dohc,8-speed automatic,midnight black metallic,black,at least 1 accident or damage reported,yes,34084.0,5,12268.200000,High,Expensive,New,3.5
2444,chevrolet,suburban 1500 lt,2015,167500.0,gasoline,355.0hp 5.3l 8 cylinder engine gasoline fuel,6-speed a/t,silver,black,none reported,yes,18000.0,10,16750.000000,Very High,Moderate,Old,5.3
2734,bmw,840 gran coupe i xdrive,2020,25793.0,gasoline,3.0l i6 24v gdi dohc turbo,8-speed automatic,black sapphire metallic,black,none reported,yes,52999.0,5,5158.600000,Medium,Luxury,New,3.0
2009,volkswagen,arteon 2.0t sel r-line,2020,15500.0,gasoline,268.0hp 2.0l 4 cylinder engine gasoline fuel,8-speed a/t,silver,black,none reported,yes,30000.0,5,3100.000000,Low,Moderate,New,2.0
975,mercedes-benz,e-class e 300 4matic,2017,36900.0,gasoline,241.0hp 2.0l 4 cylinder engine gasoline fuel,9-speed a/t,gray,beige,none reported,yes,28500.0,8,4612.500000,Medium,Moderate,Like New,2.0
53,nissan,rogue sv,2023,1094.0,gasoline,1.5l i3 12v gdi dohc turbo,automatic cvt,caspian blue,light gray,none reported,yes,30999.0,2,547.000000,Low,Expensive,New,1.5
486,chevrolet,traverse ls,2022,32117.0,gasoline,3.6l v6 24v gdi dohc,automatic,northsky blue metallic,jet black,none reported,yes,33299.0,3,10705.666667,Medium,Expensive,New,3.6
432,infiniti,qx70 base,2015,87009.0,gasoline,325.0hp 3.7l v6 cylinder engine gasoline fuel,a/t,gray,black,none reported,yes,17800.0,10,8700.900000,High,Moderate,Old,3.7

In [34]:
car_data.to_csv('../data/raw/used_cars_engineered.csv', index=False)